# Generated by Django 4.2 on 2023-04-08 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vacancy_like_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='like_num',
        ),
    ]
